### ISSUE TITLE
Compile with llvm ?

### ISSUE THREAD

**Issue by natir** [makapuf/bitbox#26]
Hello,

I see on internet we can use llvm for cross-compile to arm-none-eabi.
I'm not sure is important but maybe llvm is better compiler, or we found some other bug with llvm. I thing have many compiler is a good think for the platform.

If you are interest I can work one patch for user can select the compiler.

**Comment by makapuf** [comment]
I'm not sure at this point llvm would be a better compiler (in what metrics ? it seems gcc still has an edge for performance for baremetal). It might prove interesting to study however in the future (provided we don't complexify the build scripts for board + emulation ...). maybe trying it on a game would tell if the concept is easy. Please tell if a kernel file is not building right with llvm by example !

**Comment by andybest** [comment]
I think LLVM ld still lacks good support for linker scripts, which currently stops it being useful for this sort of thing

**Comment by makapuf** [comment]
thanks, will close for now
