### ISSUE TITLE
new bitbox bootloader doesn't allow usb input???

### ISSUE THREAD

**Issue by lowagner** [makapuf/bitbox#45]
latest bitbox bootloader (made from 2nd_boot directory) appears not to work with input.

at some point, we could also make it so that the 2nd boot loader can't flash itself.  (was trying to do this when i noticed this bug.)

**Comment by makapuf** [comment]
It's in fact worse than this, the current usb stack is for whatever reason
broken ! Please stay with / download / checkout an old kernel (pre
bigbang)  to have a good version.
Le 22 déc. 2015 6:15 PM, "Lucas O. Wagner" <notifications@github.com> a
écrit :

**Comment by makapuf** [comment]
The current status is AFAIK only the second usb works.

**Comment by lowagner** [comment]
we probably should have done another bitbox release before the new stuff.
hopefully it will get all worked out soon!

**Comment by lowagner** [comment]
i think i've gotten a working premicro branch, with some of my chiptune additions.
https://github.com/lowagner/bitbox/tree/premicro
most things compile and work, though bitbox-polar has its main sprite get its plus/minus/neutral frames messed up.  can't get bitbox-jumper to compile, though.  IIRC, bitbox-raycaster has some weird color issues, as does rapidball, though they are completely playable.

though i'm not sure how to do a pull request to create a new branch on the makapuf/bitbox sdk.

**Comment by makapuf** [comment]
Cool ! The polar frames will be easy to solve it's in the makefile. The
rest I will try to fix it. I think we can get this commit and tag it as a
basis for a stable branch and work on a master unstable branch. Can you
tell me the sha1 of the branching point ? Thanks !
Le 28 déc. 2015 6:35 AM, "Lucas O. Wagner" <notifications@github.com> a
écrit :

**Comment by lowagner** [comment]
here's the spot where i went back to (i think):
2c85801f04d440f1975ceeab20541637513e4fa4

if you like, you can create a branch ("premicro" or whatever you like) and rebase back to that, and i can do a pull request.

**Comment by makapuf** [comment]
ok I released a v0.8 branch (as a stable kernel version pre-micro and 15khz) 
How can we process from there ? Can you rebase from this and submit a pull request to this 0.8 branch ?
