### ISSUE TITLE
add simple CPU-based resizing (x2,x3) to SDL1 backend 

### ISSUE THREAD

**Issue by makapuf** [makapuf/bitbox#60]
Get an option to run sdl backends (sdl1 and maybe 2) resized x2, x3 or x4 (no fancy scale2x at start though).
This could also be ported to sdl2 renderer if needed.

**Comment by pulkomandy** [comment]
This may be useful:
http://pulkomandy.tk/projects/GrafX2/browser/trunk/src/pxdouble.c
http://pulkomandy.tk/projects/GrafX2/browser/trunk/src/pxtriple.c

(there are also "wide" and "tall" versions for pixels that have a 2:1 or 1:2 aspect ratio)

**Comment by makapuf** [comment]
fixed in bb48a8923855985a6396f4e945bc37e8a9994e7a

**Comment by makapuf** [comment]
maybe the 2x vertical can be helpful for those-not-yet-merged-in-the-kernel
RGV TV modes !

2016-03-24 10:10 GMT+01:00 Adrien Destugues <notifications@github.com>:

**Comment by pulkomandy** [comment]
Yes, some of these have very large pixels (down to 12x288px IIRc) and some have quite narrow ones (up to 900x288). We probably can't reproduce the exact aspect ratio but at least we can try to have a rough match.
I think some of the VGA modes could benefit from this as well.
