### ISSUE TITLE
python3 default distributions launch scripts with python3 instead of python2

### ISSUE THREAD

**Issue by makapuf** [makapuf/bitbox#64]
scripts should be either ported to python3 or (more short term) explicitly tagged a python2

**Comment by pulkomandy** [comment]
There are still some problems with Python3 on Haiku. But as with SDL2, I should rather take the time to fix those on Haiku side, because Python 3 is great.

**Comment by makapuf** [comment]
partially fixed by explicitly calling python2 (change 044ab3a86dbf2f9475da6b25d00946a8d8973d58 ) . py3 is another story :)
