### ISSUE TITLE
refactor libraries

### ISSUE THREAD

**Issue by makapuf** [makapuf/bitbox#71]
libraries should go in their own directories and maybe not in kernel. 
including libs in projects would imply adding them in makefile and not declaring any makefile magick. 
Also remove old chiptune code.
would then allow more libs to be distributed in main project and simplify kernel directory

**Comment by makapuf** [comment]
also maybe let events be a simple library

**Comment by lowagner** [comment]
just make sure to put out a metastable release before we do anything crazy...

**Comment by makapuf** [comment]
sure, (well the idea is just to change a few paths and adapt slightly APIs, but the 0.1 branch will be "properly" maintained - as in, not completely forgotten) 

I just now refrain from integrating interesting libs because of the current big lib directory mess (*ahem* tile16 *ahem*). splitting into useful libs + base kernel can be useful. 

Also, versioning APIs and simplifying build process can be useful. not all needs to be automated by example.

Milestone 0.2 ideas welcomed ! just add issues.

**Comment by makapuf** [comment]
the smaller kernel could allow inclusion in projects, *optionally* allowing it to be released as part of the game for easier compatibility breaking changes (by example using submodules).

**Comment by makapuf** [comment]
namely, move :  

- blitter.c, blitter.h, blitter_btc.c, blitter_sprites.c, blitter_tmap.c
- chiptune.c, chiptune.h, chiptune_engine.c, chiptune_engine.h, chiptune_player.c, chiptune_player.h
- eeprom.c, eeprom.h
- evt_queue.c /.h (in bitbox)
- sampler.c, sampler.h
- simple.c, simple.h, simple_micro.c

**Comment by lowagner** [comment]
sounds good!  what were you thinking of integrating from tile 16?

so you're thinking of having separate directories for each "category" of the current libs?

**Comment by makapuf** [comment]
well tile16 as a general tile/sprite engine could be useful ! 
I propose having one big lib dir for now, with preferably one .c and one .h per lib (with dc in .h and - maybe even one .h only) + maybe a script in /scripts (renamed /bin ?)

**Comment by makapuf** [comment]
also planning to integrate misc other libs from myself : .bmp / .tar loader, ..

**Comment by makapuf** [comment]
almost done for the refactoring in branch 0.2 , also modified a few libs (not much for now but work is still ongoing).

**Comment by makapuf** [comment]
going further, I guess it would be nice to have a subdir of /lib for each library with 
- .h/.c lib files
- test.c + Makefile of the test
- helper python scripts
- any other support files

by example : 
/lib/blitter/blitter.h and lib/blitter/example.c, /lib/blitter/tmx.py
/lib/textmode/font2c.py /lib/textmode/font8x8.png, /lib/textmode/textmode.h
/lib/chip/chip.h, /lib/chip/song2c.py

using them with 
#include "textmode/textmode.h" 
...

any thoughts ?

**Comment by lowagner** [comment]
it might help to organize things.  and when a new person comes in, they can understand what different scripts are for (at least within a category) -- which would be helpful.

**Comment by makapuf** [comment]
mostly done in branch 0.2
