### ISSUE TITLE
A compatible sdk is missing, I can't figure out how to build the project.

### ISSUE THREAD

**Issue by Jubatian** [makapuf/bitbox#91]
As of now a compatible SDK seems to be missing, the sdk subrepo link points to a nonexisting commit. The build generates several errors related to interface incompatibilities with the current sdk. I tried to check out earlier commits from the SDK (mostly those around 4 months before which align with the last commit of this repo), but neither seems to work, there are various incompatibilities.

How this should be built proper?

**Comment by makapuf** [comment]
should be fixed now with commit 65802fae90a38297c6e9464e835bf1238e5a9bb8

**Comment by Jubatian** [comment]
Thanks, from a clean clone, it builds now!
